 
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import ProviderWrapper from "@/toolkit/ProviderWrapper";
import { AuthContextProvider } from "@/context/authContext";
 
   
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   

  return (
    <html lang="en">
      <body className={inter.className}>
         
       <AuthContextProvider>

       <ProviderWrapper>

        <Navbar/>
        {children}
        <Footer/>
       </ProviderWrapper>
       </AuthContextProvider>
        
         </body>
    </html>
  );
}
